# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

# import basic packages
# -----------------------------------------------------
import pandas as pd
from snakemake.utils import validate


# load configuration and validate schema
# -----------------------------------------------------
configfile: "config/config.yaml"


validate(config, schema="schemas/config.schema.yaml")


# read sample sheet
SAMPLES = pd.read_csv(config["samples"], sep="\t", dtype={"sample": str})[
    "sample"
].tolist()


# load rules
# -----------------------------------------------------
include: "rules/variant_processing.smk"


# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# target rules
# -----------------------------------------------------
rule all:
    default_target: True
    input:
        "results/merged/all_samples.vcf.gz",
