# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

# import basic packages
# -----------------------------------------------------
import pandas as pd
from snakemake.utils import validate


# load configuration and validate schema
# -----------------------------------------------------
configfile: "config/config.yaml"


validate(config, schema="schemas/config.schema.yaml")


# read sample sheet
SAMPLES = pd.read_csv(config["samples"], sep="\t", dtype={"sample": str})[
    "sample"
].tolist()


# load rules
# -----------------------------------------------------
include: "rules/variant_processing.smk"


# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n=== Haplotype-Resolved PLM Scoring Workflow ===")
    print(f"Total samples to process: {len(SAMPLES)}")
    print(f"Samples: {', '.join(SAMPLES)}")
    print(
        f"VQSR Threshold: {config["variant_processing"]["filter_variants"]["vqsr_threshold"]}"
    )
    print("===============================================\n")


onsuccess:
    print("\n=== Workflow completed successfully! ===")
    print("All sample VCFs filtered, concatenated, and merged.")
    print(
        "Output available at: results/merged/all_samples.vcf.gz\n"
    )  # TODO: to update with new versions


onerror:
    print("\n=== Workflow failed! ===")
    print(
        "Check individual job log files in the 'logs/' directory for error details.\n"
    )


# target rules
# -----------------------------------------------------
rule all:
    default_target: True
    input:
        "results/merged/all_samples.vcf.gz",
