# config/config.yaml

# ==============================================================================
# PIPELINE ANALYSIS CONFIGURATION
# ==============================================================================

# --- Input Files & Metadata ---
samples: "config/samples.tsv"

# --- System & Resources ---
temp_dir: "results/temp"

# --- Variant Processing Rules Configuration ---
variant_processing:
  filter_variants:
    vqsr_threshold: 99.9
