# config/config.yaml

# ==============================================================================
# PIPELINE ANALYSIS CONFIGURATION
# ==============================================================================

# --- Input Files & Metadata ---
samples: "config/samples.tsv"

# --- Variant Filtering & Processing (BCFtools) ---
bcftools:
  vqsr_threshold: 99.9
  # pass_only: true
  # min_qual: 30
