# .test/config/config.yaml

# ==============================================================================
# PIPELINE ANALYSIS CONFIGURATION
# ==============================================================================

# --- Input Files & Metadata ---
samples: "config/samples.tsv"

# --- System & Resources ---
temp_dir: "results/temp"

# --- Variant Processing Rules Configuration ---
variant_processing:
  filter_variants:
    vqsr_threshold: 99.9

# --- Phasing Rules Configuration ---
phasing:
  shapeit5_phasing:
    gmap_template: "resources/gmaps/{chr}.b38.gmap.gz"
