# .test/config/config.yaml

# ==============================================================================
# PIPELINE ANALYSIS CONFIGURATION
# ==============================================================================

# --- Input Files & Metadata ---
samples: "config/samples.tsv"

# --- Variant Processing Rules Configuration ---
variant_processing:
  filter_variants:
    vqsr_threshold: 99.9
