# workflow/schemas/config.schema.yaml

$schema: "https://json-schema.org/draft/2020-12/schema"
description: "Validation schema for config.yaml"

type: object

properties:
  samples:
    type: string
    description: "Path to the TSV file containing the sample table."

  # variant_processing:
  #   type: object
  #   description: "Processing parameters for genomic variants."

# Top-level mandatory fields in config.yaml
required:
  - samples
  # - variant_processing
